[package]
name = "CoinStorage"
version = "1.0.0"
upgrade_policy = "immutable"

[addresses]
aptos_std = "0x1"
coin_storage = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
